// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ExpenseManager.Api.Data.Migrations;

[DbContext(typeof(ExpenseManager.Api.Data.AppDbContext))]
[Migration("20260819110000_NormalizeGoalBalances")]
partial class NormalizeGoalBalances
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
}
