// <auto-generated />
using System;
using ExpenseManager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpenseManager.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260806085424_AddGoalAvailabilityWorkflow")]
    partial class AddGoalAvailabilityWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpenseManager.Api.Domain.AccountVerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<string>("PendingEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("pending_email");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("purpose");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_account_verification_codes");

                    b.HasIndex("UserId", "Purpose", "CreatedAt")
                        .HasDatabaseName("ix_account_verification_codes_user_id_purpose_created_at");

                    b.ToTable("account_verification_codes", (string)null);
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MonthYear")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("month_year");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_budgets");

                    b.HasIndex("CategoryId", "UserId")
                        .HasDatabaseName("ix_budgets_category_id_user_id");

                    b.HasIndex("UserId", "CategoryId", "MonthYear")
                        .IsUnique()
                        .HasDatabaseName("ix_budgets_user_id_category_id_month_year");

                    b.ToTable("budgets", t =>
                        {
                            t.HasCheckConstraint("ck_budgets_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_budgets_month_year", "month_year ~ '^\\d{4}-(0[1-9]|1[0-2])$'");
                        });
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasAlternateKey("Id", "UserId")
                        .HasName("ak_categories_id_user_id");

                    b.HasAlternateKey("Id", "UserId", "Type")
                        .HasName("ak_categories_id_user_id_type");

                    b.HasIndex("UserId", "Name", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_user_id_name_type");

                    b.ToTable("categories", t =>
                        {
                            t.HasCheckConstraint("ck_categories_type", "type IN ('INCOME', 'EXPENSE')");
                        });
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CurrentAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("current_amount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<long>("TargetAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("target_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_goals");

                    b.HasIndex("UserId", "Name")
                        .HasDatabaseName("ix_goals_user_id_name");

                    b.ToTable("goals", t =>
                        {
                            t.HasCheckConstraint("ck_goals_amounts", "target_amount > 0 AND current_amount >= 0 AND current_amount <= target_amount");

                            t.HasCheckConstraint("ck_goals_status", "status IN ('ACTIVE', 'READY_TO_COMPLETE', 'COMPLETED', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.GoalHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action_type");

                    b.Property<long>("AmountAdded")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_added");

                    b.Property<long?>("BalanceAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<long?>("RequestedAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("requested_amount");

                    b.HasKey("Id")
                        .HasName("pk_goal_histories");

                    b.HasIndex("GoalId", "Date")
                        .HasDatabaseName("ix_goal_histories_goal_id_date");

                    b.ToTable("goal_histories", t =>
                        {
                            t.HasCheckConstraint("ck_goal_histories_action", "action_type IN ('FUND', 'COMPLETE', 'CANCEL')");

                            t.HasCheckConstraint("ck_goal_histories_amounts", "((action_type = 'FUND' AND amount_added > 0) OR (action_type IN ('COMPLETE', 'CANCEL') AND amount_added = 0)) AND (requested_amount IS NULL OR requested_amount > 0) AND (balance_after IS NULL OR balance_after >= 0)");
                        });
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_json");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scope");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_records_expires_at");

                    b.HasIndex("UserId", "Scope", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_idempotency_records_user_id_scope_key");

                    b.ToTable("idempotency_records");
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.OcrResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LinesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("lines_json");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_version");

                    b.Property<decimal>("OverallConfidence")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("overall_confidence");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parser_version");

                    b.Property<long>("ProcessingTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("processing_time_ms");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<DateOnly?>("ReceiptDate")
                        .HasColumnType("date")
                        .HasColumnName("receipt_date");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<string>("StoreName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("store_name");

                    b.Property<long?>("TotalAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_amount");

                    b.Property<long?>("VatAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("vat_amount");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("warnings_json");

                    b.HasKey("Id")
                        .HasName("pk_ocr_results");

                    b.HasIndex("ReceiptId")
                        .IsUnique()
                        .HasDatabaseName("ix_ocr_results_receipt_id");

                    b.ToTable("ocr_results", t =>
                        {
                            t.HasCheckConstraint("ck_ocr_results_amounts_and_confidence", "overall_confidence BETWEEN 0 AND 1 AND (total_amount IS NULL OR total_amount > 0) AND (vat_amount IS NULL OR vat_amount >= 0) AND (total_amount IS NULL OR vat_amount IS NULL OR vat_amount <= total_amount)");
                        });
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Classification")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("classification");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<int>("ProcessingAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("processing_attempts");

                    b.Property<DateTime?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_receipts");

                    b.HasAlternateKey("Id", "UserId")
                        .HasName("ak_receipts_id_user_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_receipts_user_id_created_at");

                    b.HasIndex("Status", "NextRetryAt", "LeaseExpiresAt", "CreatedAt")
                        .HasDatabaseName("ix_receipts_status_next_retry_at_lease_expires_at_created_at");

                    b.ToTable("receipts", t =>
                        {
                            t.HasCheckConstraint("ck_receipts_file_size_positive", "file_size > 0");

                            t.HasCheckConstraint("ck_receipts_processing_attempts", "processing_attempts >= 0");
                        });
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.ReceiptImage", b =>
                {
                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.HasKey("ReceiptId")
                        .HasName("pk_receipt_images");

                    b.ToTable("receipt_images");
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ReplacedByTokenId")
                        .HasDatabaseName("ix_refresh_tokens_replaced_by_token_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_user_id_expires_at");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_month");

                    b.Property<int>("Hour")
                        .HasColumnType("integer")
                        .HasColumnName("hour");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Minute")
                        .HasColumnType("integer")
                        .HasColumnName("minute");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_reminders");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reminders_user_id");

                    b.ToTable("reminders", t =>
                        {
                            t.HasCheckConstraint("ck_reminders_schedule", "day_of_month BETWEEN 1 AND 31 AND hour BETWEEN 0 AND 23 AND minute BETWEEN 0 AND 59");
                        });
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid?>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<string>("StoreName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("store_name");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("GoalId")
                        .IsUnique()
                        .HasDatabaseName("ix_transactions_goal_id");

                    b.HasIndex("ReceiptId")
                        .IsUnique()
                        .HasDatabaseName("ix_transactions_receipt_id");

                    b.HasIndex("ReceiptId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_transactions_receipt_id_user_id");

                    b.HasIndex("CategoryId", "UserId", "Type")
                        .HasDatabaseName("ix_transactions_category_id_user_id_type");

                    b.HasIndex("UserId", "TransactionDate", "CreatedAt", "Id")
                        .HasDatabaseName("ix_transactions_user_id_transaction_date_created_at_id");

                    b.ToTable("transactions", t =>
                        {
                            t.HasCheckConstraint("ck_transactions_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_transactions_type", "type IN ('INCOME', 'EXPENSE')");
                        });
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_verified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("integer")
                        .HasColumnName("token_version");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", t =>
                        {
                            t.HasCheckConstraint("ck_users_email_lowercase", "email = lower(email)");
                        });
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.AccountVerificationCode", b =>
                {
                    b.HasOne("ExpenseManager.Api.Domain.User", "User")
                        .WithMany("VerificationCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_verification_codes_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.Budget", b =>
                {
                    b.HasOne("ExpenseManager.Api.Domain.User", "User")
                        .WithMany("Budgets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budgets_users_user_id");

                    b.HasOne("ExpenseManager.Api.Domain.Category", "Category")
                        .WithMany("Budgets")
                        .HasForeignKey("CategoryId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_budgets_categories_category_id_user_id");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.Category", b =>
                {
                    b.HasOne("ExpenseManager.Api.Domain.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categories_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.Goal", b =>
                {
                    b.HasOne("ExpenseManager.Api.Domain.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_goals_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.GoalHistory", b =>
                {
                    b.HasOne("ExpenseManager.Api.Domain.Goal", "Goal")
                        .WithMany("History")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_goal_histories_goals_goal_id");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.IdempotencyRecord", b =>
                {
                    b.HasOne("ExpenseManager.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_idempotency_records_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.OcrResult", b =>
                {
                    b.HasOne("ExpenseManager.Api.Domain.Receipt", "Receipt")
                        .WithOne("OcrResult")
                        .HasForeignKey("ExpenseManager.Api.Domain.OcrResult", "ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ocr_results_receipts_receipt_id");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.Receipt", b =>
                {
                    b.HasOne("ExpenseManager.Api.Domain.User", "User")
                        .WithMany("Receipts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_receipts_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.ReceiptImage", b =>
                {
                    b.HasOne("ExpenseManager.Api.Domain.Receipt", "Receipt")
                        .WithOne("Image")
                        .HasForeignKey("ExpenseManager.Api.Domain.ReceiptImage", "ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_receipt_images_receipts_receipt_id");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.RefreshToken", b =>
                {
                    b.HasOne("ExpenseManager.Api.Domain.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_refresh_tokens_refresh_tokens_replaced_by_token_id");

                    b.HasOne("ExpenseManager.Api.Domain.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.Reminder", b =>
                {
                    b.HasOne("ExpenseManager.Api.Domain.User", "User")
                        .WithMany("Reminders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reminders_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.Transaction", b =>
                {
                    b.HasOne("ExpenseManager.Api.Domain.Goal", "Goal")
                        .WithOne("CompletionTransaction")
                        .HasForeignKey("ExpenseManager.Api.Domain.Transaction", "GoalId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transactions_goals_goal_id");

                    b.HasOne("ExpenseManager.Api.Domain.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_users_user_id");

                    b.HasOne("ExpenseManager.Api.Domain.Receipt", "Receipt")
                        .WithOne("Transaction")
                        .HasForeignKey("ExpenseManager.Api.Domain.Transaction", "ReceiptId", "UserId")
                        .HasPrincipalKey("ExpenseManager.Api.Domain.Receipt", "Id", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_transactions_receipts_receipt_id_user_id");

                    b.HasOne("ExpenseManager.Api.Domain.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId", "UserId", "Type")
                        .HasPrincipalKey("Id", "UserId", "Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_categories_category_id_user_id_type");

                    b.Navigation("Category");

                    b.Navigation("Goal");

                    b.Navigation("Receipt");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.Category", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.Goal", b =>
                {
                    b.Navigation("CompletionTransaction");

                    b.Navigation("History");
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.Receipt", b =>
                {
                    b.Navigation("Image")
                        .IsRequired();

                    b.Navigation("OcrResult");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("ExpenseManager.Api.Domain.User", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Categories");

                    b.Navigation("Goals");

                    b.Navigation("Receipts");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reminders");

                    b.Navigation("Transactions");

                    b.Navigation("VerificationCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
