// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ExpenseManager.Api.Data.Migrations;

[DbContext(typeof(ExpenseManager.Api.Data.AppDbContext))]
[Migration("20260819091000_RemoveTransactionGoalLink")]
public partial class RemoveTransactionGoalLink
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // The current model is represented by AppDbContextModelSnapshot. The
        // migration only changes the legacy transaction/goal link.
    }
}
