namespace ExpenseManager.Api.Services;

public sealed class CategoryRuleSet
{
    public IReadOnlyList<CategoryPatternRule> PatternRules { get; }
    public IReadOnlyList<CategoryCompositionRule> CompositionRules { get; }
    public IReadOnlyList<MerchantBrandProfile> BrandProfiles { get; }

    public CategoryRuleSet(
        IReadOnlyList<CategoryPatternRule>? patternRules = null,
        IReadOnlyList<CategoryCompositionRule>? compositionRules = null,
        IReadOnlyList<MerchantBrandProfile>? brandProfiles = null)
    {
        PatternRules = patternRules ?? DefaultPatternRules();
        CompositionRules = compositionRules ?? DefaultCompositionRules();
        BrandProfiles = (brandProfiles ?? []).Select(profile => profile with
        {
            Contribution = Math.Clamp(profile.Contribution, 0m, 4m)
        }).ToList();
    }

    private static IReadOnlyList<CategoryPatternRule> DefaultPatternRules() =>
    [
        // FOOD AND DRINK: prepared food is deliberately separate from generic
        // grocery tokens so retail context can suppress the latter.
        Rule("food-prepared-strong", SemanticExpenseCategory.FOOD_AND_DRINK,
            CategoryRuleKind.STRONG_PHRASE, CategoryEvidenceSource.PRODUCT,
            CategoryRuleScope.CONTENT, 12m,
            ["TRA SUA", "MILK TEA", "BUBBLE TEA", "CA PHE SUA", "BREWED COFFEE",
             "COM PHAN", "COM VAN PHONG", "BUN BO", "PHO BO", "BANH MI",
             "COMBO MEAL", "SET MENU", "FOOD DELIVERY"],
            ["PREPARED_FOOD"], "Phát hiện món ăn hoặc đồ uống được chế biến.", true),
        Rule("food-prepared-moderate", SemanticExpenseCategory.FOOD_AND_DRINK,
            CategoryRuleKind.MODERATE_PHRASE, CategoryEvidenceSource.PRODUCT,
            CategoryRuleScope.CONTENT, 7m,
            ["ESPRESSO", "LATTE", "CAPPUCCINO", "AMERICANO", "PHINDI", "SINH TO",
             "NUOC EP", "TRAI CAY", "GA RAN", "PIZZA", "HAMBURGER", "COM CHIEN",
             "MI XAO", "HU TIEU", "DESSERT"],
            ["PREPARED_FOOD", "FOOD_PRODUCT"], "Phát hiện món ăn/đồ uống có khả năng dùng ngay.", true),
        Rule("food-product-weak", SemanticExpenseCategory.FOOD_AND_DRINK,
            CategoryRuleKind.WEAK_TOKEN, CategoryEvidenceSource.PRODUCT,
            CategoryRuleScope.CONTENT, 2m,
            ["TEA", "COFFEE", "TRA", "SUA", "NUOC", "COM", "BUN", "MI",
             "BANH", "BIA", "JUICE", "MILK", "RICE", "NOODLE", "CHICKEN", "BEEF"],
            ["FOOD_PRODUCT"], "Tên thực phẩm/đồ uống đơn lẻ; chỉ là bằng chứng yếu."),
        Rule("food-merchant-descriptor", SemanticExpenseCategory.FOOD_AND_DRINK,
            CategoryRuleKind.MERCHANT_DESCRIPTOR, CategoryEvidenceSource.MERCHANT,
            CategoryRuleScope.MERCHANT, 12m,
            ["NHA HANG", "RESTAURANT", "QUAN AN", "EATERY", "QUAN CA PHE",
             "COFFEE SHOP", "MILK TEA SHOP", "FOOD COURT", "CANTEEN", "CANG TIN",
             "BISTRO", "FAST FOOD", "PIZZERIA"],
            ["FOOD_SERVICE_CONTEXT"], "Merchant thể hiện mô hình dịch vụ ăn uống.", true),
        Rule("food-merchant-medium", SemanticExpenseCategory.FOOD_AND_DRINK,
            CategoryRuleKind.MERCHANT_DESCRIPTOR, CategoryEvidenceSource.MERCHANT,
            CategoryRuleScope.MERCHANT, 8m,
            ["CAFE", "COFFEE", "BAKERY", "TIEM BANH", "TRA SUA"],
            ["FOOD_SERVICE_CONTEXT"], "Merchant có mô tả cafe/đồ uống/tiệm bánh.", true),
        Rule("food-merchant-weak-product", SemanticExpenseCategory.FOOD_AND_DRINK,
            CategoryRuleKind.WEAK_TOKEN, CategoryEvidenceSource.MERCHANT,
            CategoryRuleScope.MERCHANT, 4m,
            ["TEA", "TRA", "JUICE", "SMOOTHIE"],
            ["FOOD_NAMED_MERCHANT"],
            "Tên merchant chứa loại đồ uống nhưng vẫn cần order/product context."),
        Tag("food-order-context", CategoryRuleKind.MODERATE_PHRASE,
            CategoryRuleScope.CONTENT,
            ["DINE IN", "IN STORE", "TAKE AWAY", "TAKEAWAY", "MANG VE", "TABLE NO",
             "BAN SO", "GOI MON", "ORDER NO", "TOPPING", "SIZE M", "SIZE L"],
            ["FOOD_ORDER_CONTEXT"], "Có ngữ cảnh gọi món hoặc sử dụng tại quán."),
        Rule("food-document", SemanticExpenseCategory.FOOD_AND_DRINK,
            CategoryRuleKind.DOCUMENT_TYPE, CategoryEvidenceSource.DOCUMENT_TYPE,
            CategoryRuleScope.CONTENT, 14m,
            ["PHIEU GOI MON", "RESTAURANT BILL", "KITCHEN ORDER", "TABLE BILL",
             "FOOD DELIVERY RECEIPT"],
            ["FOOD_SERVICE_CONTEXT"], "Chứng từ thuộc dịch vụ ăn uống."),

        // TRANSPORT.
        Rule("transport-strong", SemanticExpenseCategory.TRANSPORT,
            CategoryRuleKind.STRONG_PHRASE, CategoryEvidenceSource.CONTENT,
            CategoryRuleScope.BOTH, 15m,
            ["CUOC TAXI", "CUOC CHUYEN DI", "TAXI FARE", "TRIP FARE", "VE XE BUYT",
             "BUS TICKET", "VE XE KHACH", "VE TAU", "TRAIN TICKET", "VE MAY BAY",
             "FLIGHT TICKET", "AIR TICKET", "PHI GUI XE", "PARKING FEE", "TOLL FEE",
             "PHI CAU DUONG", "PHI CAO TOC", "TIEN XANG", "FUEL PURCHASE"],
            ["TRANSPORT_CONTEXT"], "Cụm từ xác định chi phí di chuyển.", true),
        Rule("transport-merchant", SemanticExpenseCategory.TRANSPORT,
            CategoryRuleKind.MERCHANT_DESCRIPTOR, CategoryEvidenceSource.MERCHANT,
            CategoryRuleScope.MERCHANT, 11m,
            ["TAXI", "RIDE HAILING", "BUS OPERATOR", "NHA XE", "AIRLINE", "RAILWAY",
             "TRAIN STATION", "BUS STATION", "PETROL STATION", "GAS STATION",
             "TRAM XANG", "PARKING", "TOLL OPERATOR"],
            ["TRANSPORT_CONTEXT"], "Merchant cung cấp vận tải/nhiên liệu/gửi xe.", true),
        Tag("ticket-token", CategoryRuleKind.NEUTRAL, CategoryRuleScope.CONTENT,
            ["TICKET", "VE"], ["TICKET"], "Ticket cần modifier để phân loại."),
        Tag("transport-mode", CategoryRuleKind.MODERATE_PHRASE, CategoryRuleScope.CONTENT,
            ["BUS", "XE BUYT", "TRAIN", "TAU HOA", "FLIGHT", "AIRLINE", "PASSENGER",
             "BOARDING", "DEPARTURE", "ARRIVAL"],
            ["TRANSPORT_MODE"], "Phát hiện phương tiện vận tải."),
        Tag("parking-context", CategoryRuleKind.MODERATE_PHRASE, CategoryRuleScope.BOTH,
            ["PARKING", "GUI XE", "DO XE", "BAI GIU XE"],
            ["PARKING_CONTEXT"], "Phát hiện ngữ cảnh gửi/đỗ xe."),
        Rule("transport-document", SemanticExpenseCategory.TRANSPORT,
            CategoryRuleKind.DOCUMENT_TYPE, CategoryEvidenceSource.DOCUMENT_TYPE,
            CategoryRuleScope.CONTENT, 16m,
            ["BOARDING PASS", "E TICKET ITINERARY", "PASSENGER TICKET", "TOLL RECEIPT",
             "FUEL INVOICE", "TRIP RECEIPT"],
            ["TRANSPORT_CONTEXT"], "Chứng từ vận tải rõ ràng.", true),

        // SHOPPING and retail structure.
        Rule("shopping-retail-descriptor", SemanticExpenseCategory.SHOPPING,
            CategoryRuleKind.MERCHANT_DESCRIPTOR, CategoryEvidenceSource.MERCHANT,
            CategoryRuleScope.MERCHANT, 10m,
            ["SIEU THI", "SUPERMARKET", "MINIMART", "CUA HANG TIEN LOI",
             "CONVENIENCE STORE", "GROCERY STORE", "DEPARTMENT STORE", "RETAIL STORE",
             "TAP HOA"],
            ["RETAIL_CONTEXT"], "Merchant là điểm bán lẻ/tạp hóa.", true),
        Rule("shopping-domain-strong", SemanticExpenseCategory.SHOPPING,
            CategoryRuleKind.STRONG_PHRASE, CategoryEvidenceSource.CONTENT,
            CategoryRuleScope.BOTH, 13m,
            ["QUAN AO", "CLOTHING STORE", "FASHION STORE", "DO GIA DUNG",
             "HOUSEHOLD GOODS", "DIEN MAY", "ELECTRONICS STORE", "MY PHAM",
             "COSMETICS STORE", "VAN PHONG PHAM", "HARDWARE STORE", "HOME APPLIANCE"],
            ["RETAIL_CONTEXT"], "Lĩnh vực bán lẻ hàng hóa rõ ràng.", true),
        Tag("product-table", CategoryRuleKind.MODERATE_PHRASE, CategoryRuleScope.CONTENT,
            ["SKU", "BARCODE", "MA HANG", "MA SAN PHAM", "UNIT PRICE", "GIA BAN",
             "DON GIA", "MEMBER PRICE", "LOYALTY POINT", "RETURN POLICY", "WARRANTY",
             "BAO HANH"],
            ["PRODUCT_TABLE"], "Có cấu trúc bảng hàng hóa bán lẻ."),
        Tag("packaged-goods", CategoryRuleKind.WEAK_TOKEN, CategoryRuleScope.CONTENT,
            ["CHAI", "LON", "HOP", "GOI", "PACK", "BOTTLE", "CAN", "BOX"],
            ["PACKAGED_GOODS"], "Có đơn vị hàng hóa đóng gói."),
        Rule("shopping-document", SemanticExpenseCategory.SHOPPING,
            CategoryRuleKind.DOCUMENT_TYPE, CategoryEvidenceSource.DOCUMENT_TYPE,
            CategoryRuleScope.CONTENT, 12m,
            ["RETAIL INVOICE", "PURCHASE RECEIPT", "PHIEU BAN HANG", "HOA DON BAN LE",
             "PHIEU XUAT HANG"],
            ["RETAIL_CONTEXT"], "Chứng từ bán lẻ.", true),

        // HOUSING.
        Rule("housing-rent-strong", SemanticExpenseCategory.HOUSING,
            CategoryRuleKind.STRONG_PHRASE, CategoryEvidenceSource.CONTENT,
            CategoryRuleScope.CONTENT, 16m,
            ["TIEN THUE NHA", "TIEN THUE PHONG", "TIEN NHA THANG", "HOUSE RENT",
             "ROOM RENT", "MONTHLY RENT", "APARTMENT RENT", "PHI QUAN LY CHUNG CU",
             "PROPERTY MANAGEMENT FEE", "APARTMENT SERVICE FEE"],
            ["RENT_LEASE", "PROPERTY_CONTEXT"], "Chi phí thuê hoặc quản lý nhà ở.", true),
        Tag("rent-lease", CategoryRuleKind.MODERATE_PHRASE, CategoryRuleScope.CONTENT,
            ["RENT", "LEASE", "THUE NHA", "THUE PHONG", "RENTAL PERIOD"],
            ["RENT_LEASE"], "Phát hiện thuê/lease."),
        Tag("property-context", CategoryRuleKind.MODERATE_PHRASE, CategoryRuleScope.BOTH,
            ["APARTMENT", "CAN HO", "TENANT", "LANDLORD", "PROPERTY", "PHONG TRO",
             "BAN QUAN LY CHUNG CU"],
            ["PROPERTY_CONTEXT"], "Phát hiện bất động sản/người thuê."),
        Rule("home-service", SemanticExpenseCategory.HOUSING,
            CategoryRuleKind.MERCHANT_DESCRIPTOR, CategoryEvidenceSource.MERCHANT,
            CategoryRuleScope.BOTH, 10m,
            ["HOME MAINTENANCE", "PROPERTY MAINTENANCE", "PLUMBER", "ELECTRICIAN",
             "RENOVATION CONTRACTOR", "AIR CONDITIONING SERVICE", "PEST CONTROL SERVICE",
             "HOME CLEANING SERVICE", "SUA CHUA NHA", "BAO TRI CAN HO"],
            ["HOME_SERVICE"], "Dịch vụ dành cho nhà ở."),
        Tag("repair-token", CategoryRuleKind.WEAK_TOKEN, CategoryRuleScope.CONTENT,
            ["REPAIR", "MAINTENANCE", "SUA CHUA", "BAO TRI", "LABOR CHARGE", "WORK ORDER"],
            ["REPAIR_SERVICE"], "Có nội dung sửa chữa/bảo trì."),
        Rule("housing-document", SemanticExpenseCategory.HOUSING,
            CategoryRuleKind.DOCUMENT_TYPE, CategoryEvidenceSource.DOCUMENT_TYPE,
            CategoryRuleScope.CONTENT, 15m,
            ["RENT RECEIPT", "LEASE PAYMENT RECEIPT", "PHIEU THU TIEN NHA",
             "PROPERTY MANAGEMENT INVOICE", "HOME REPAIR WORK ORDER"],
            ["PROPERTY_CONTEXT"], "Chứng từ thuê/bảo trì nhà ở.", true),

        // ENTERTAINMENT. Ticket itself remains neutral; modifiers compose it.
        Tag("admission-context", CategoryRuleKind.MODERATE_PHRASE, CategoryRuleScope.CONTENT,
            ["ENTRANCE", "ADMISSION", "VAO CONG", "THAM QUAN", "MUSEUM", "BAO TANG",
             "ATTRACTION", "VISITOR PASS"],
            ["ADMISSION_CONTEXT"], "Phát hiện ngữ cảnh vào cửa/tham quan."),
        Tag("event-context", CategoryRuleKind.MODERATE_PHRASE, CategoryRuleScope.CONTENT,
            ["MOVIE", "CINEMA", "XEM PHIM", "CONCERT", "HOA NHAC", "EVENT", "SU KIEN",
             "THEME PARK", "KHU VUI CHOI"],
            ["ENTERTAINMENT_EVENT"], "Phát hiện phim/sự kiện/khu vui chơi."),
        Rule("entertainment-strong", SemanticExpenseCategory.ENTERTAINMENT,
            CategoryRuleKind.STRONG_PHRASE, CategoryEvidenceSource.CONTENT,
            CategoryRuleScope.CONTENT, 15m,
            ["KARAOKE ROOM CHARGE", "NAP TIEN TRO CHOI", "GAME CREDIT",
             "BOWLING LANE", "ARCADE CARD"],
            ["ENTERTAINMENT_CONTEXT"], "Chứng từ/dịch vụ giải trí rõ ràng.", true),
        Rule("entertainment-gaming", SemanticExpenseCategory.ENTERTAINMENT,
            CategoryRuleKind.STRONG_PHRASE, CategoryEvidenceSource.CONTENT,
            CategoryRuleScope.BOTH, 14m,
            ["INTERNET CAFE", "GAMING CENTER", "PLAY TIME", "GAME CREDIT",
             "ARCADE CARD", "NAP TIEN TRO CHOI"],
            ["ENTERTAINMENT_CONTEXT"], "Dịch vụ trò chơi/giải trí theo thời gian hoặc credit.", true),
        Rule("entertainment-merchant", SemanticExpenseCategory.ENTERTAINMENT,
            CategoryRuleKind.MERCHANT_DESCRIPTOR, CategoryEvidenceSource.MERCHANT,
            CategoryRuleScope.MERCHANT, 11m,
            ["CINEMA", "RAP CHIEU PHIM", "THEATER", "MUSEUM", "BAO TANG", "KARAOKE",
             "AMUSEMENT PARK", "THEME PARK", "BOWLING", "ARCADE", "ZOO", "AQUARIUM"],
            ["ENTERTAINMENT_CONTEXT"], "Merchant là địa điểm giải trí/tham quan.", true),
        Rule("entertainment-document", SemanticExpenseCategory.ENTERTAINMENT,
            CategoryRuleKind.DOCUMENT_TYPE, CategoryEvidenceSource.DOCUMENT_TYPE,
            CategoryRuleScope.CONTENT, 17m,
            ["ADMISSION TICKET", "ENTRANCE TICKET", "MOVIE TICKET", "EVENT TICKET",
             "ATTRACTION PASS", "VISITOR PASS"],
            ["ENTERTAINMENT_CONTEXT"], "Loại chứng từ vào cửa/giải trí.", true),

        // HEALTH.
        Rule("health-clinical-strong", SemanticExpenseCategory.HEALTH,
            CategoryRuleKind.STRONG_PHRASE, CategoryEvidenceSource.CONTENT,
            CategoryRuleScope.CONTENT, 15m,
            ["KHAM BENH", "PHI KHAM", "MEDICAL CONSULTATION", "CONSULTATION FEE",
             "VIEN PHI", "HOSPITAL FEE", "DON THUOC", "PRESCRIPTION MEDICINE",
             "XET NGHIEM", "LAB TEST", "X RAY", "SIEU AM", "ULTRASOUND",
             "DENTAL TREATMENT", "NHO RANG", "TIEM CHUNG", "VACCINATION"],
            ["CLINICAL_CONTEXT"], "Dịch vụ khám/chữa bệnh rõ ràng.", true),
        Rule("health-merchant", SemanticExpenseCategory.HEALTH,
            CategoryRuleKind.MERCHANT_DESCRIPTOR, CategoryEvidenceSource.MERCHANT,
            CategoryRuleScope.MERCHANT, 12m,
            ["NHA THUOC", "PHARMACY", "DRUGSTORE", "BENH VIEN", "HOSPITAL",
             "PHONG KHAM", "CLINIC", "NHA KHOA", "DENTAL CLINIC", "MEDICAL CENTER",
             "VACCINATION CENTER", "MEDICAL LABORATORY"],
            ["PHARMACY_CLINICAL_CONTEXT"], "Merchant là cơ sở y tế/nhà thuốc.", true),
        Tag("medicine-product", CategoryRuleKind.WEAK_TOKEN, CategoryRuleScope.CONTENT,
            ["THUOC", "MEDICINE", "DRUG", "VITAMIN", "TABLET", "CAPSULE", "DUOC PHAM"],
            ["MEDICINE_PRODUCT"], "Sản phẩm y tế cần pharmacy/clinical context."),
        Rule("health-document", SemanticExpenseCategory.HEALTH,
            CategoryRuleKind.DOCUMENT_TYPE, CategoryEvidenceSource.DOCUMENT_TYPE,
            CategoryRuleScope.CONTENT, 17m,
            ["PRESCRIPTION", "DON THUOC", "MEDICAL INVOICE", "HOSPITAL RECEIPT",
             "PHIEU THU VIEN PHI", "DENTAL INVOICE"],
            ["CLINICAL_CONTEXT"], "Chứng từ y tế rõ ràng.", true),

        // EDUCATION.
        Rule("education-fee-strong", SemanticExpenseCategory.EDUCATION,
            CategoryRuleKind.STRONG_PHRASE, CategoryEvidenceSource.CONTENT,
            CategoryRuleScope.CONTENT, 16m,
            ["HOC PHI", "TUITION FEE", "SCHOOL FEE", "PHI NHAP HOC", "ENROLLMENT FEE",
             "PHI GHI DANH", "REGISTRATION FEE", "PHI KHOA HOC", "COURSE FEE",
             "PHI DAO TAO", "TRAINING FEE", "LE PHI THI", "EXAM FEE", "TUTORING FEE"],
            ["EDUCATION_FEE"], "Khoản phí giáo dục/đào tạo rõ ràng.", true),
        Rule("education-merchant", SemanticExpenseCategory.EDUCATION,
            CategoryRuleKind.MERCHANT_DESCRIPTOR, CategoryEvidenceSource.MERCHANT,
            CategoryRuleScope.MERCHANT, 11m,
            ["TRUONG HOC", "SCHOOL", "UNIVERSITY", "COLLEGE", "ACADEMY",
             "TRAINING CENTER", "TRUNG TAM DAO TAO", "LANGUAGE CENTER",
             "TRUNG TAM NGOAI NGU", "TUTORING CENTER", "VOCATIONAL SCHOOL"],
            ["SCHOOL_TRAINING_CONTEXT"], "Merchant là cơ sở giáo dục/đào tạo.", true),
        Tag("student-course", CategoryRuleKind.MODERATE_PHRASE, CategoryRuleScope.CONTENT,
            ["STUDENT ID", "MA HOC VIEN", "SEMESTER", "HOC KY", "ACADEMIC YEAR",
             "NAM HOC", "CLASS CODE", "COURSE CODE", "COURSE", "STUDENT"],
            ["STUDENT_COURSE_CONTEXT"], "Phát hiện học viên/khóa học."),
        Tag("fee-token", CategoryRuleKind.WEAK_TOKEN, CategoryRuleScope.CONTENT,
            ["FEE", "PHI", "HOC PHI", "TUITION"],
            ["FEE_CONTEXT"], "Token phí cần context nghiệp vụ."),
        Tag("book-product", CategoryRuleKind.WEAK_TOKEN, CategoryRuleScope.CONTENT,
            ["BOOK", "SACH", "PEN", "BUT", "NOTEBOOK", "VO"],
            ["BOOK_STATIONERY_PRODUCT"], "Sách/văn phòng phẩm cần phân biệt retail và giáo dục."),
        Rule("bookstore-context", SemanticExpenseCategory.SHOPPING,
            CategoryRuleKind.MERCHANT_DESCRIPTOR, CategoryEvidenceSource.MERCHANT,
            CategoryRuleScope.BOTH, 10m,
            ["BOOKSTORE", "NHA SACH", "STATIONERY STORE", "VAN PHONG PHAM"],
            ["BOOKSTORE_RETAIL_CONTEXT", "RETAIL_CONTEXT"], "Merchant bán lẻ sách/văn phòng phẩm."),
        Rule("education-document", SemanticExpenseCategory.EDUCATION,
            CategoryRuleKind.DOCUMENT_TYPE, CategoryEvidenceSource.DOCUMENT_TYPE,
            CategoryRuleScope.CONTENT, 17m,
            ["TUITION RECEIPT", "SCHOOL FEE RECEIPT", "PHIEU THU HOC PHI",
             "ENROLLMENT INVOICE", "COURSE REGISTRATION RECEIPT", "EXAM FEE RECEIPT"],
            ["EDUCATION_FEE"], "Chứng từ học phí/đăng ký học.", true),

        // BILLS.
        Rule("bills-strong", SemanticExpenseCategory.BILLS,
            CategoryRuleKind.STRONG_PHRASE, CategoryEvidenceSource.CONTENT,
            CategoryRuleScope.CONTENT, 16m,
            ["HOA DON TIEN DIEN", "ELECTRICITY BILL", "HOA DON TIEN NUOC", "WATER BILL",
             "CUOC INTERNET", "INTERNET BILL", "CUOC DIEN THOAI", "PHONE BILL",
             "MOBILE POSTPAID BILL", "UTILITY BILL", "CUOC TRUYEN HINH", "CABLE TV BILL",
             "PHI THUE BAO", "MONTHLY SUBSCRIPTION"],
            ["UTILITY_CONTEXT"], "Hóa đơn tiện ích/thuê bao rõ ràng.", true),
        Rule("bills-merchant", SemanticExpenseCategory.BILLS,
            CategoryRuleKind.MERCHANT_DESCRIPTOR, CategoryEvidenceSource.MERCHANT,
            CategoryRuleScope.MERCHANT, 10m,
            ["ELECTRICITY COMPANY", "POWER COMPANY", "WATER SUPPLY", "UTILITY PROVIDER",
             "TELECOM", "MOBILE OPERATOR", "INTERNET SERVICE PROVIDER", "CABLE PROVIDER"],
            ["UTILITY_CONTEXT"], "Merchant là nhà cung cấp tiện ích/viễn thông.", true),
        Tag("utility-token", CategoryRuleKind.MODERATE_PHRASE, CategoryRuleScope.BOTH,
            ["ELECTRICITY", "TIEN DIEN", "WATER SUPPLY", "TIEN NUOC", "INTERNET",
             "TELECOM", "MOBILE POSTPAID", "UTILITY", "CABLE TV"],
            ["UTILITY_CONTEXT"], "Phát hiện loại tiện ích."),
        Tag("billing-period", CategoryRuleKind.MODERATE_PHRASE, CategoryRuleScope.CONTENT,
            ["BILLING PERIOD", "KY HOA DON", "DUE DATE", "CURRENT CHARGE",
             "PREVIOUS BALANCE", "USAGE CHARGE", "MONTHLY STATEMENT"],
            ["BILLING_PERIOD"], "Phát hiện chu kỳ thanh toán."),
        Tag("meter-customer", CategoryRuleKind.MODERATE_PHRASE, CategoryRuleScope.CONTENT,
            ["CUSTOMER CODE", "MA KHACH HANG", "METER NUMBER", "SO CONG TO",
             "METER READING", "CHI SO DONG HO", "KWH", "M3 CONSUMPTION"],
            ["METER_CUSTOMER_CONTEXT"], "Phát hiện mã khách hàng/công tơ/tiêu thụ."),
        Rule("bills-document", SemanticExpenseCategory.BILLS,
            CategoryRuleKind.DOCUMENT_TYPE, CategoryEvidenceSource.DOCUMENT_TYPE,
            CategoryRuleScope.CONTENT, 17m,
            ["UTILITY BILL", "BILLING STATEMENT", "PAYMENT NOTICE", "THONG BAO TIEN DIEN",
             "THONG BAO TIEN NUOC", "TELECOM INVOICE"],
            ["UTILITY_CONTEXT"], "Chứng từ thanh toán tiện ích.", true),

        // Global neutral metadata. These rules intentionally only emit tags
        // and never contribute to a category score.
        Tag("neutral-metadata", CategoryRuleKind.NEUTRAL, CategoryRuleScope.CONTENT,
            ["TOTAL", "SUBTOTAL", "VAT", "CASHIER", "TERMINAL", "CHANGE DUE", "DATE",
             "RECEIPT", "ITEM", "STORE", "THANH TIEN", "TONG CONG", "DON GIA"],
            ["NEUTRAL_METADATA"], "Metadata hóa đơn không mang ý nghĩa category.")
    ];

    private static IReadOnlyList<CategoryCompositionRule> DefaultCompositionRules() =>
    [
        Compose("food-service-product", SemanticExpenseCategory.FOOD_AND_DRINK, 9m,
            ["FOOD_SERVICE_CONTEXT"], ["PREPARED_FOOD", "FOOD_PRODUCT"], [],
            "Dịch vụ ăn uống đi cùng món/đồ uống."),
        Compose("food-order-product", SemanticExpenseCategory.FOOD_AND_DRINK, 8m,
            ["FOOD_ORDER_CONTEXT"], ["PREPARED_FOOD", "FOOD_PRODUCT"], ["RETAIL_CONTEXT"],
            "Ngữ cảnh gọi món đi cùng món/đồ uống."),
        Compose("retail-packaged-table", SemanticExpenseCategory.SHOPPING, 10m,
            ["RETAIL_CONTEXT", "PACKAGED_GOODS", "PRODUCT_TABLE"], [], [],
            "Bán lẻ với hàng đóng gói và bảng sản phẩm.",
            new Dictionary<SemanticExpenseCategory, decimal>
            {
                [SemanticExpenseCategory.FOOD_AND_DRINK] = -6m
            }),
        Compose("retail-packaged-structure", SemanticExpenseCategory.SHOPPING, 8m,
            ["PACKAGED_GOODS", "PRODUCT_TABLE"], [], ["FOOD_ORDER_CONTEXT"],
            "Bảng hàng hóa đóng gói có cấu trúc bán lẻ."),
        Compose("transport-ticket", SemanticExpenseCategory.TRANSPORT, 18m,
            ["TRANSPORT_MODE", "TICKET"], [], ["ADMISSION_CONTEXT", "ENTERTAINMENT_EVENT"],
            "Ticket được bổ nghĩa bởi phương tiện vận tải.",
            new Dictionary<SemanticExpenseCategory, decimal>
            {
                [SemanticExpenseCategory.ENTERTAINMENT] = -14m
            }),
        Compose("parking-ticket", SemanticExpenseCategory.TRANSPORT, 15m,
            ["PARKING_CONTEXT"], ["TICKET", "FEE_CONTEXT"], [],
            "Phí/ticket gửi hoặc đỗ xe."),
        Compose("admission-ticket", SemanticExpenseCategory.ENTERTAINMENT, 18m,
            ["ADMISSION_CONTEXT", "TICKET"], [], ["TRANSPORT_MODE"],
            "Ticket được bổ nghĩa bởi entrance/admission/tham quan.",
            new Dictionary<SemanticExpenseCategory, decimal>
            {
                [SemanticExpenseCategory.TRANSPORT] = -14m,
                [SemanticExpenseCategory.FOOD_AND_DRINK] = -10m
            }),
        Compose("event-ticket", SemanticExpenseCategory.ENTERTAINMENT, 18m,
            ["ENTERTAINMENT_EVENT", "TICKET"], [], ["TRANSPORT_MODE"],
            "Ticket phim/sự kiện/khu vui chơi.",
            new Dictionary<SemanticExpenseCategory, decimal>
            {
                [SemanticExpenseCategory.TRANSPORT] = -14m
            }),
        Compose("clinical-medicine", SemanticExpenseCategory.HEALTH, 16m,
            ["PHARMACY_CLINICAL_CONTEXT", "MEDICINE_PRODUCT"], [], [],
            "Thuốc trong context nhà thuốc/cơ sở y tế."),
        Compose("retail-medicine", SemanticExpenseCategory.SHOPPING, 8m,
            ["RETAIL_CONTEXT", "MEDICINE_PRODUCT", "PRODUCT_TABLE"], [], [],
            "Sản phẩm y tế được bán như hàng hóa retail.",
            new Dictionary<SemanticExpenseCategory, decimal>
            {
                [SemanticExpenseCategory.HEALTH] = -6m
            }),
        Compose("education-fee-context", SemanticExpenseCategory.EDUCATION, 16m,
            ["SCHOOL_TRAINING_CONTEXT", "STUDENT_COURSE_CONTEXT", "FEE_CONTEXT"], [], [],
            "Cơ sở giáo dục, học viên/khóa học và khoản phí."),
        Compose("bookstore-product", SemanticExpenseCategory.SHOPPING, 10m,
            ["BOOKSTORE_RETAIL_CONTEXT", "BOOK_STATIONERY_PRODUCT"], [], [],
            "Sách/văn phòng phẩm trong context bán lẻ.",
            new Dictionary<SemanticExpenseCategory, decimal>
            {
                [SemanticExpenseCategory.EDUCATION] = -6m
            }),
        Compose("utility-billing", SemanticExpenseCategory.BILLS, 16m,
            ["UTILITY_CONTEXT", "BILLING_PERIOD", "METER_CUSTOMER_CONTEXT"], [], [],
            "Tiện ích có chu kỳ và mã khách hàng/công tơ."),
        Compose("rent-property", SemanticExpenseCategory.HOUSING, 16m,
            ["RENT_LEASE", "PROPERTY_CONTEXT"], [], [],
            "Thuê/lease trong context nhà ở."),
        Compose("home-repair", SemanticExpenseCategory.HOUSING, 15m,
            ["HOME_SERVICE", "REPAIR_SERVICE"], [], ["RETAIL_CONTEXT"],
            "Dịch vụ sửa chữa/bảo trì tại nhà."),
        Compose("home-service-property", SemanticExpenseCategory.HOUSING, 8m,
            ["HOME_SERVICE", "PROPERTY_CONTEXT"], [], ["RETAIL_CONTEXT"],
            "Dịch vụ nhà ở đi cùng ngữ cảnh căn hộ/bất động sản."),
        Compose("hardware-repair-product", SemanticExpenseCategory.SHOPPING, 10m,
            ["RETAIL_CONTEXT", "REPAIR_SERVICE", "PRODUCT_TABLE"], [], [],
            "Vật tư sửa chữa được mua trong context bán lẻ.",
            new Dictionary<SemanticExpenseCategory, decimal>
            {
                [SemanticExpenseCategory.HOUSING] = -8m
            })
    ];

    private static CategoryPatternRule Rule(
        string id,
        SemanticExpenseCategory category,
        CategoryRuleKind kind,
        CategoryEvidenceSource source,
        CategoryRuleScope scope,
        decimal weight,
        IReadOnlyList<string> patterns,
        IReadOnlyList<string> tags,
        string reason,
        bool fuzzy = false) =>
        new(id, category, kind, source, scope, weight, patterns, tags, reason, fuzzy);

    private static CategoryPatternRule Tag(
        string id,
        CategoryRuleKind kind,
        CategoryRuleScope scope,
        IReadOnlyList<string> patterns,
        IReadOnlyList<string> tags,
        string reason) =>
        new(id, null, kind, CategoryEvidenceSource.CONTENT, scope, 0m, patterns, tags, reason);

    private static CategoryCompositionRule Compose(
        string id,
        SemanticExpenseCategory category,
        decimal weight,
        IReadOnlyList<string> all,
        IReadOnlyList<string> any,
        IReadOnlyList<string> forbidden,
        string reason,
        IReadOnlyDictionary<SemanticExpenseCategory, decimal>? penalties = null) =>
        new(id, category, weight, all, any, forbidden, reason, penalties);
}
